Repository smaranjitghose/Upcharika, pull requests merged in 2021-06, with the labels that each got.

#16 Improving button UI
  lib/homePage.dart
  lib/main.dart
Labels: PR: reviewed-approved

#17 Exit Flash bug Fixed
  lib/homePage.dart
Labels: LGMSOC21, PR: reviewed-changes-requested, PR: unreviewed

#21 Adding a timer on heart rate screen
  lib/homePage.dart
Labels: PR: unreviewed

#23 Added a simple onboarding screen.
  .flutter-plugins
  .flutter-plugins-dependencies
  .gitignore
  assets/onboard1.png
  assets/onboard2.png
  assets/onboard3.png
  lib/main.dart
  lib/onboardingScreen.dart
  pubspec.yaml
Labels: LGMSOC21, 🟧 Level3

#24 Store various values of heart rate
  images/nodata.png
  lib/HeartRate.dart
  lib/homePage.dart
  pubspec.yaml
Labels: PR: unreviewed

#30 Exit BPM process
  lib/homePage.dart
Labels: PR: unreviewed

#25 bottom navigation added
  lib/Dashboard.dart
  lib/HeartRate.dart
  lib/Home.dart
  lib/Level.dart
  lib/main.dart
Labels: PR: unreviewed

#35 Fixed Issue #4
  assets/Upcharika.png
  lib/Home.dart
  lib/onboardingScreen.dart
  pubspec.yaml
Labels: LGMSOC21, PR: reviewed-approved, 🟨 Level2

#33 Adding image to assets folder
  assets/nofile.png
  lib/HeartRate.dart
Labels: PR: reviewed-approved

#37 PR for the issue Timer Enhancement
  android/app/src/main/AndroidManifest.xml
  lib/homePage.dart
  lib/main.dart
  lib/onboardingScreen.dart
  lib/timer.dart
  pubspec.yaml
Labels: PR: reviewed-approved

#38 On Board Screen Logic
  lib/main.dart
  lib/onboardingScreen.dart
Labels: LGMSOC21, PR: reviewed-approved, 🟧 Level3
